"""
This code time evolves DMRG ground states using TDVP
The ensuing Krylov subspace of states then gives a new ground state energy estimate
Requires TenPy v1.0.2 and a directory called "data/" to save results
"""
import numpy as np
from scipy.linalg import eigh # generalized eigenvalue
from matplotlib import pyplot as plt
import pickle
from joblib import Parallel, delayed # parallelize generation of data
import pyscf
# TenPy Imports, TenPy Version 1.0.2
import tenpy as tp
from tenpy.models import CouplingMPOModel, NearestNeighborModel
from tenpy.models import lattice
from tenpy.models.molecular import MolecularModel
# Uncomment the line below if you want TenPy's intrinsic logging 
tp.tools.misc.setup_logging(to_stdout="INFO")

# get ground state of Hubbard model using DMRG at dixed bond dimension chi
# Lx, Ly are system size, chi = DMRG bond dimension, U = Hubbard repulsion, psi_init is initial state
# Returns tuple of energy and ground state
def get_gnd_hubbard(model, chi, psi_init=None):
	# By default, start with a state that has half-filling (one electron per site)
	if psi_init is None:
		product_state = ["up", "down"] * (len(model.lat.mps_sites()) // 2) # start in semi-Néel state 
		n_sites = len(model.lat.mps_sites())
		if len(product_state) != n_sites:
			product_state.append("up")
		# product_state = ["up", "down"]  * (Lx * Ly // 2) # start in semi-Néel state 
		psi = tp.MPS.from_product_state(model.lat.mps_sites(), product_state)
	else:
		psi = psi_init

	# Set up DMRG parameters and precision (bond dimension beyond chi is truncated)
	dmrg_params = {'mixer': True, 'trunc_params': {'chi_max': chi, 'svd_min': 1e-9},
		'max_E_err': 1e-9, 'max_S_err': 1e-6, 'min_sweeps': 20, 'max_sweeps': 50, 'max_trunc_err': None,
		'max_N_sites_per_ring': None}
	engine = tp.TwoSiteDMRGEngine(psi, model, dmrg_params)
	
	# Run DMRG and return energy and ground state
	E, psi = engine.run()
	print(f"E = {E}")
	
	return (E, psi)

# Evolve a (ground) state "psi_gnd" of Hubbard model using TDVP at fixed bond dimenion chi
# Evolve from time 0 to time T in steps of dt
# Returns tuple of energy and ground state
def evolve_gnd_hubbard(psi_gnd, model, chi, T=3, dt=0.2):
	# parameters for each step of TDVP
	num_steps = int(T / dt)
	time_params = {'start_time': 0, 'dt': dt, 'N_steps': 1,
		'trunc_params': {'chi_max': chi, 'svd_min': 1.e-10, 'trunc_cut': None}, 'max_N_sites_per_ring': None}
	
	# evolve the inputted state psi_gnd in place
	engine = tp.TwoSiteTDVPEngine(psi_gnd, model, time_params)

	# Save a copy of the evolved state at each time step
	states = [psi_gnd.copy()] # initial state at t = 0
	for step in range(num_steps):
		print(f"Time = {dt*step}")
		engine.run()
		states.append(psi_gnd.copy())

	return states

# create krylov data by evolving a single DMRG ground state using several different TDVP algorithms
# each time evolution has a different maximum bond dimension (specified by chitimes)
# data saved is target and overlap operators in krylov subspace generated by time evolution
# given states {|v0>, |v1>, ... , |vi>} these are H = <vi | Hamiltonian | vj> and S = <vi | vj>
def make_diff_timechi(psi_dmrg, model_ref, dt=0.2, T=3, chitimes=None):
	times = np.arange(0, T, dt)

	# this is the bond dimension of the inputted DMRG state
	chi_dmrg = np.max(psi_dmrg.chi)
	print("Chi (DMRG): ", chi_dmrg)

	# helper function to parallelize
	def make_data(chi_time):
		print(f"\n\nSTARTING chi={chi_time}\n\n")
		
		# Evolve the initial state with maximum bond dimension chi_time
		states = evolve_gnd_hubbard(psi_dmrg.copy(), model_ref, chi=chi_time, T=T, dt=dt)
		
		# create overlap and target matrices
		N = len(states)
		S, H = [np.zeros((N, N), dtype=complex) for _ in range(2)]

		# fill off-diagonal elements with overlaps and hamiltonian expectation values
		for i in range(N):
			for j in range(i+1, N):
				S[i, j] = states[i].overlap(states[j]) # < vi | vj >
				H[i, j] = tp.MPOEnvironment(states[i], model_ref.H_MPO, states[j]).full_contraction(0) # < vi | H | vj >
		H += H.conj().T
		S += S.conj().T

		# fill diagonal elements 
		for i in range(N):
			S[i, i] = states[i].overlap(states[i]).real
			H[i, i] = model_ref.H_MPO.expectation_value(states[i]).real

		# save data in pickle file in directory "data/"
		# label data by initial DMRG bond dimension and time evolution bond dimension
		with open(f'data/krylov_chidmrg{chi_dmrg}_chitime{chi_time}.p', 'wb') as h:
			pickle.dump([times, S, H], h)

		print(f"\n\nDUMPED chi={chi_time}\n\n")

	# Generate data for a list of chi_time values in parallel
	results = Parallel(n_jobs=-1, backend='loky')(delayed(make_data)(chi_time) for chi_time in chitimes)

def make_plots(chi_dmrg, chi_times):
	plt.figure()

	# loop through all of time evolution bond dimensions
	for i, chi_time in enumerate(chi_times):
		# load krylov data
		with open(f'data/krylov_chidmrg{chi_dmrg}_chitime{chi_time}.p', 'rb') as h:
			times, S, H = pickle.load(h)

		N = S.shape[0] # size of krylov subspace
		delta_E = [] # Difference between krylov ansatz and true ground state energy
		
		# Try to keep successively more krylov states and plot energies that result
		for keep in range(1, N + 1):
			# keep only parts of target/overlap matrices
			print(f"Keeping {keep} Krylov states")
			H0, S0 = H[:keep, :keep], S[:keep, :keep] 
			
			# CHECK THAT OVERLAPS MATRIX IS NOT BADLY CONDITIONED
			# If it is good enough, solve generalized eigenvalue problem in krylov subspace
			# H | v > = E S | v >
			svals = np.linalg.svd(S0, compute_uv=False)
			cond = svals.max() / svals.min()
			print("Condition Number:", cond)
			try:
				vals, vecs = eigh(H0, S0)
			except np.linalg.LinAlgError:
				print("HAD CONVERGENCE PROBLEM")
				eps = 1e-12
				correction = eps*np.eye(S0.shape[0])
				vals, vecs = eigh(H0, S0 + correction)

			# record difference btwn krylov ansatz and the true ground state energy 
			delta_E.append(vals[0]) 
			
		minsize = min(len(times), len(delta_E))

		# plot the series of energy differences for this particular time evolution process  
		plt.plot(times[:minsize], delta_E[:minsize], 'o-', 
			label=r'$\chi_\mathrm{time} = $' +str(chi_time) if chi_time in [chi_dmrg, 2*chi_dmrg, 4*chi_dmrg] else None, 
			c=plt.get_cmap('RdYlBu')((chi_time-chi_dmrg)/(4*chi_dmrg-chi_dmrg)), zorder=2, 
			linewidth=4 if chi_time in [chi_dmrg, 2*chi_dmrg, 4*chi_dmrg] else 1)

	
	# load previously computed DMRG energies and states at a three bond dimensions
	with open(f'data/gnd_chi{chi_dmrg}.p', 'rb') as h:
		E_dmrg_this, psi_this = pickle.load(h)
	with open(f'data/gnd_chi{2 * chi_dmrg}.p', 'rb') as h:
		E_dmrg_next, psi_next = pickle.load(h)
	with open(f'data/gnd_chi{4 * chi_dmrg}.p', 'rb') as h:
		E_dmrg_best, psi_best = pickle.load(h)

	# Plot other DMRG values as horizontal lines for reference
	plt.axhline(E_dmrg_this, c='red', linewidth=2, linestyle='dashed', label=fr'DMRG $\chi=$ {chi_dmrg}')
	plt.axhline(E_dmrg_next, c='orange', linewidth=2, linestyle='dashed', label=fr'DMRG $\chi=$ {2 * chi_dmrg}')
	plt.axhline(E_dmrg_best, c='blue', linewidth=2, linestyle='dashed', label=fr'DMRG $\chi=$ {4 * chi_dmrg}')
	plt.ylabel(r'$\Delta E_\mathrm{gnd}$', fontsize=14)
	plt.xlabel('Time evolved (~Krylov states kept)', fontsize=14)
	plt.legend(ncols=2)
	plt.title(fr'Starting from DMRG at $\chi = ${chi_dmrg}, HF.', fontsize=14)
	return plt.gcf()

def main():
	chidmrg = 24
	# Get V_ijkl and h_ij for the HF molecule.
	mol = pyscf.M(
		atom = 'H 0 0 0; F 0 0 1.1',  # in Angstrom
		basis = 'ccpvdz',
		symmetry = True,
	)
	orb = mol.RHF().run().mo_coeff
	v_ijkl = mol.intor('int2e', aosym='s1')
	h_ij = mol.intor('int1e_nuc') + mol.intor('int1e_kin')
	print("One- and two-body tensor dimensions:")
	print(h_ij.shape)
	print(v_ijkl.shape)
	# Make a TeNPy molecular model
	params = {"one_body_tensor": h_ij, "two_body_tensor": v_ijkl}
	mol_model = MolecularModel(params)
	print(mol_model.lat.N_sites_per_ring)

	# generate and save DMRG data for initial states at 3 different bond dimensions 
	for chi in [chidmrg, 2 * chidmrg, 4 * chidmrg]:
		E, psi = get_gnd_hubbard(mol_model, chi, psi_init=None)
		with open(f'data/gnd_chi{chi}.p', 'wb') as handle:
			pickle.dump([E, psi], handle)
	print("Done making DMRG data")

	# generate a few bond dimensions to time evolve with
	def bond_dims(n):
		return [n + k*n//4 for k in range(5)]
	chitimes = bond_dims(chidmrg) + bond_dims(2*chidmrg)[1:]
	print("Time evolution bond dimensions: ", chitimes)

	# Make data
	with open(f'data/gnd_chi{chidmrg}.p', 'rb') as handle:
		E_init, psi_init = pickle.load(handle)
	make_diff_timechi(psi_init, mol_model, chitimes=chitimes, dt=0.2, T=3)
	print("DONE making time evolution data")

	# Make plots of krylov energy estimates
	make_plots(chi_dmrg=chidmrg, chi_times=chitimes)
	plt.show()

if __name__ == '__main__':
	main()
