"""
This code time evolves DMRG ground states using TDVP
The ensuing Krylov subspace of states then gives a new ground state energy estimate
Requires TenPy v1.0.2 and a directory called "data/" to save results
"""
import numpy as np
from scipy.linalg import eigh # generalized eigenvalue
from matplotlib import pyplot as plt
import pickle
from joblib import Parallel, delayed # parallelize generation of data

# TenPy Imports, TenPy Version 1.0.2
import tenpy as tp
from tenpy.models import CouplingMPOModel, NearestNeighborModel
from tenpy.models import lattice
# Uncomment the line below if you want TenPy's intrinsic logging 
tp.tools.misc.setup_logging(to_stdout="INFO")

# Exact energy of ground state of:
# 4 x 2 square lattice Hubbard model with U=8, t=1, at half-filling
E_gnd = -3.02592280569069 # lowest energy
E_antignd = 35.0258 # highest energy state

# Create a Square Lattice Hubbard Model as an MPO in Tenpy
class HubbardSquare2D(CouplingMPOModel):
	
	# initialize sites of the model to have spin-1/2 fermions
	# conserve particle number but not spin, work at half-filling
	def init_sites(self, model_params):
		conserve = model_params.get('cons_N', 'N') 
		filling = model_params.get('filling', 1.)
		site = tp.networks.site.SpinHalfFermionSite(cons_N='N', cons_Sz=None, filling=1)
		return site

	# Initialize a square lattice of dimensions Lx x Ly
	# Open boundary conditions by default in both directions 
	def init_lattice(self, model_params):
		Lx = model_params.get('Lx', 4)
		Ly = model_params.get('Ly', 2)
		bc_x = model_params.get('bc_x', 'open') 
		bc_y = model_params.get('bc_y', 'open')
		bc_MPS = model_params.get('bc_MPS', 'finite')
		lattice = tp.models.lattice.Square(Lx, Ly, site=self.init_sites(model_params), 
							bc=[bc_x, bc_y], bc_MPS=bc_MPS)
		# ordering of sites is up-down snake: start bottom left, end top right
		return lattice

	# Define the Hamiltonian
	def init_terms(self, model_params):
		t = model_params.get('t', 1.0) # hopping
		U = model_params.get('U', 8.0) # onsite Hubbard repulsion
		mu = model_params.get('mu', 0) # chemical potential 
		for u1, u2, dx in self.lat.pairs['nearest_neighbors']:
			self.add_coupling(t, u1, 'Cdd', u2, 'Cd', dx, plus_hc=True)  # h.c. Cdagger_down C_down
			self.add_coupling(t, u1, 'Cdu', u2, 'Cu', dx, plus_hc=True)  # h.c. Cdagger_up C_up
		for v in range(len(self.lat.unit_cell)):
			self.add_onsite(U, v, 'NuNd') # Hubbard n_up n_down term
		for v in range(len(self.lat.unit_cell)):
			self.add_onsite(mu, v, 'Nu') # chemical potential
			self.add_onsite(mu, v, 'Nd') # chemical potential

# get ground state of Hubbard model using DMRG at dixed bond dimension chi
# Lx, Ly are system size, chi = DMRG bond dimension, U = Hubbard repulsion, psi_init is initial state
# Returns tuple of energy and ground state
def get_gnd_hubbard(Lx, Ly, chi, U=8, psi_init=None):
	params = {'Lx': Lx, 'Ly':Ly, 'U':U, 'cons_N':'N', 'filling':1}
	model = HubbardSquare2D(params)

	# By default, start with a state that has half-filling (one electron per site)
	if psi_init is None:
		product_state = ["up", "down"]  * (Lx * Ly // 2) # start in semi-Néel state 
		psi = tp.MPS.from_product_state(model.lat.mps_sites(), product_state)
	else:
		psi = psi_init

	# Set up DMRG parameters and precision (bond dimension beyond chi is truncated)
	dmrg_params = {'mixer': True, 'trunc_params': {'chi_max': chi, 'svd_min': 1e-9},
		'max_E_err': 1e-9, 'max_S_err': 1e-6, 'min_sweeps': 20, 'max_sweeps': 50, 'max_trunc_err': None}
	engine = tp.TwoSiteDMRGEngine(psi, model, dmrg_params)
	
	# Run DMRG and return energy and ground state
	E, psi = engine.run()
	print(f"E = {E}")
	
	return (E, psi)

# Evolve a (ground) state "psi_gnd" of Hubbard model using TDVP at fixed bond dimenion chi
# Evolve from time 0 to time T in steps of dt
# Returns tuple of energy and ground state
def evolve_gnd_hubbard(psi_gnd, Lx, Ly, chi, U=8, T=3, dt=0.2):
	params = {'Lx': Lx, 'Ly':Ly, 'U':U, 'cons_N':'N', 'filling':1}
	model = HubbardSquare2D(params)
	
	# parameters for each step of TDVP
	num_steps = int(T / dt)
	time_params = {'start_time': 0, 'dt': dt, 'N_steps': 1,
		'trunc_params': {'chi_max': chi, 'svd_min': 1.e-10, 'trunc_cut': None} }
	
	# evolve the inputted state psi_gnd in place
	engine = tp.TwoSiteTDVPEngine(psi_gnd, model, time_params)

	# Save a copy of the evolved state at each time step
	states = [psi_gnd.copy()] # initial state at t = 0
	for step in range(num_steps):
		print(f"Time = {dt*step}")
		engine.run()
		states.append(psi_gnd.copy())

	return states

# create krylov data by evolving a single DMRG ground state using several different TDVP algorithms
# each time evolution has a different maximum bond dimension (specified by chitimes)
# data saved is target and overlap operators in krylov subspace generated by time evolution
# given states {|v0>, |v1>, ... , |vi>} these are H = <vi | Hamiltonian | vj> and S = <vi | vj>
def make_diff_timechi(psi_dmrg, dt=0.2, T=3, U=8, Lx=4, Ly=2, chitimes=None):
	times = np.arange(0, T, dt)
	model_ref = HubbardSquare2D({'Lx': Lx, 'Ly': Ly, 'U':U, 'mu':0}) # Hamiltonian to calculate overlaps

	# this is the bond dimension of the inputted DMRG state
	chi_dmrg = np.max(psi_dmrg.chi)
	print("Chi (DMRG): ", chi_dmrg)

	# helper function to parallelize
	def make_data(chi_time):
		print(f"\n\nSTARTING chi={chi_time}\n\n")
		
		# Evolve the initial state with maximum bond dimension chi_time
		states = evolve_gnd_hubbard(psi_dmrg.copy(), Lx=Lx, Ly=Ly, chi=chi_time, U=U, T=T, dt=dt)
		
		# create overlap and target matrices
		N = len(states)
		S, H = [np.zeros((N, N), dtype=complex) for _ in range(2)]

		# fill off-diagonal elements with overlaps and hamiltonian expectation values
		for i in range(N):
			for j in range(i+1, N):
				S[i, j] = states[i].overlap(states[j]) # < vi | vj >
				H[i, j] = tp.MPOEnvironment(states[i], model_ref.H_MPO, states[j]).full_contraction(0) # < vi | H | vj >
		H += H.conj().T
		S += S.conj().T

		# fill diagonal elements 
		for i in range(N):
			S[i, i] = states[i].overlap(states[i]).real
			H[i, i] = model_ref.H_MPO.expectation_value(states[i]).real

		# save data in pickle file in directory "data/"
		# label data by initial DMRG bond dimension and time evolution bond dimension
		with open(f'data/krylov_chidmrg{chi_dmrg}_chitime{chi_time}.p', 'wb') as h:
			pickle.dump([times, S, H], h)

		print(f"\n\nDUMPED chi={chi_time}\n\n")

	# Generate data for a list of chi_time values in parallel
	results = Parallel(n_jobs=-1, backend='loky')(delayed(make_data)(chi_time) for chi_time in chitimes)

def make_plots(chi_dmrg, chi_times):
	plt.figure()

	# loop through all of time evolution bond dimensions
	for i, chi_time in enumerate(chi_times):
		# load krylov data
		with open(f'data/krylov_chidmrg{chi_dmrg}_chitime{chi_time}.p', 'rb') as h:
			times, S, H = pickle.load(h)

		N = S.shape[0] # size of krylov subspace
		delta_E = [] # Difference between krylov ansatz and true ground state energy
		
		# Try to keep successively more krylov states and plot energies that result
		for keep in range(1, N + 1):
			# keep only parts of target/overlap matrices
			print(f"Keeping {keep} Krylov states")
			H0, S0 = H[:keep, :keep], S[:keep, :keep] 
			
			# CHECK THAT OVERLAPS MATRIX IS NOT BADLY CONDITIONED
			# If it is good enough, solve generalized eigenvalue problem in krylov subspace
			# H | v > = E S | v >
			svals = np.linalg.svd(S0, compute_uv=False)
			cond = svals.max() / svals.min()
			print("Condition Number:", cond)
			try:
				vals, vecs = eigh(H0, S0)
			except np.linalg.LinAlgError:
				print("HAD CONVERGENCE PROBLEM")
				eps = 1e-12
				correction = eps*np.eye(S0.shape[0])
				vals, vecs = eigh(H0, S0 + correction)

			# record difference btwn krylov ansatz and the true ground state energy 
			delta_E.append(vals[0] - E_gnd) 
			
		minsize = min(len(times), len(delta_E))

		# plot the series of energy differences for this particular time evolution process  
		plt.plot(times[:minsize], delta_E[:minsize], 'o-', 
			label=r'$\chi_\mathrm{time} = $' +str(chi_time) if chi_time in [chi_dmrg, 2*chi_dmrg, 3*chi_dmrg, 4*chi_dmrg] else None, 
			c=plt.get_cmap('RdYlBu')((chi_time-chi_dmrg)/(4*chi_dmrg-chi_dmrg)), zorder=2, 
			linewidth=4 if chi_time in [chi_dmrg, 2*chi_dmrg, 4*chi_dmrg] else 1)

	
	# load previously computed DMRG energies and states at a three bond dimensions
	with open(f'data/gnd_chi{chi_dmrg}.p', 'rb') as h:
		E_dmrg_this, psi_this = pickle.load(h)
	with open(f'data/gnd_chi{2 * chi_dmrg}.p', 'rb') as h:
		E_dmrg_next, psi_next = pickle.load(h)
	with open(f'data/gnd_chi{3 * chi_dmrg}.p', 'rb') as h:
		E_dmrg_second_best, psi_second_best = pickle.load(h)
	with open(f'data/gnd_chi{4 * chi_dmrg}.p', 'rb') as h:
		E_dmrg_best, psi_best = pickle.load(h)

	# Plot other DMRG values as horizontal lines for reference
	plt.axhline(E_dmrg_this - E_gnd, c='red', linewidth=2, linestyle='dashed', label=fr'DMRG $\chi=$ {chi_dmrg}')
	plt.axhline(E_dmrg_next - E_gnd, c='orange', linewidth=2, linestyle='dashed', label=fr'DMRG $\chi=$ {2 * chi_dmrg}')
	plt.axhline(E_dmrg_second_best - E_gnd, c='blue', linewidth=2, linestyle='dashed', label=fr'DMRG $\chi=$ {3 * chi_dmrg}')
	plt.axhline(E_dmrg_best - E_gnd, c='blue', linewidth=2, linestyle='dashed', label=fr'DMRG $\chi=$ {4 * chi_dmrg}')
	plt.ylabel(r'$\Delta E_\mathrm{gnd}$', fontsize=14)
	plt.xlabel('Time evolved (~Krylov states kept)', fontsize=14)
	plt.yscale("log")
	plt.legend(ncols=2)
	plt.title(fr'Starting from DMRG at $\chi = ${chi_dmrg} (Square Hubbard U=8)', fontsize=14)
	return plt.gcf()

def main():
	U = 8
	Lx, Ly = 4, 2
	chidmrg = 16

	# generate and save DMRG data for initial states at 3 different bond dimensions 
	for chi in [chidmrg, 2 * chidmrg, 3 * chidmrg, 4 * chidmrg]:
		E, psi = get_gnd_hubbard(Lx, Ly, chi, U=8, psi_init=None)
		with open(f'data/gnd_chi{chi}.p', 'wb') as handle:
			pickle.dump([E, psi], handle)
	print("Done making DMRG data")

	# generate a few bond dimensions to time evolve with
	def bond_dims(n):
		return [n + k*n//4 for k in range(5)]
	chitimes = bond_dims(chidmrg) + bond_dims(2*chidmrg)[1:]
	print("Time evolution bond dimensions: ", chitimes)

	# Make data
	# We will use the ground state of the F-H model
	# with a different value of U as the starting state.
	# This might get us away from the fixed point of the TDVP procedure.
	# with open(f'data/gnd_chi{chidmrg}.p', 'rb') as handle:
		# E_init, psi_init = pickle.load(handle)
	U_prime = U - 3.0
	E_init, psi_init = get_gnd_hubbard(Lx, Ly, chidmrg, U_prime, psi_init=None)
	psi_init = evolve_gnd_hubbard(psi_init, Lx, Ly, chidmrg, U=U_prime, T=1e-1, dt=1e-4)[-1]
	make_diff_timechi(psi_init, chitimes=chitimes, dt=0.2, T=3, U=8, Lx=4, Ly=2)
	print("DONE making time evolution data")

	# Make plots of krylov energy estimates
	make_plots(chi_dmrg=chidmrg, chi_times=chitimes)
	plt.show()

if __name__ == '__main__':
	main()
